server:
  port: ${PORT:8083}

spring:
  application:
    name: analysis-service

  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}

eureka:
  client:
    serviceUrl:
      defaultZone: https://eureka-server-ppq0.onrender.com/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: false
    hostname: analysis-service-qf75.onrender.com   # ✅ its own URL, from your earlier log
    non-secure-port: 443
    secure-port-enabled: true
    secure-port: 443