server:
  port: ${PORT:8081}
  forward-headers-strategy: framework

spring:
  application:
    name: auth-service

  config:
    import: configserver:${CONFIG_SERVER_URL:http://localhost:8888}

  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

eureka:
  client:
    serviceUrl:
      defaultZone: https://eureka-server-ppq0.onrender.com/eureka/
    fetch-registry: true
    register-with-eureka: true

  instance:
    prefer-ip-address: false
    hostname: auth-service-p0ex.onrender.com
    non-secure-port-enabled: false
    secure-port-enabled: true
    secure-port: 443
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30
