server:
  port: ${PORT:8081}

spring:
  application:
    name: auth-service

  config:
    import: optional:configserver:${CONFIG_SERVER_URL:}

eureka:
  client:
    serviceUrl:
      defaultZone: https://eureka-server-ppq0.onrender.com/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: false
    hostname: api-gateway-qkib.onrender.com