server:
  port: ${PORT:8081}
  forward-headers-strategy: framework

spring:
  application:
    name: auth-service

  config:
    import: optional:configserver:${CONFIG_SERVER_URL:}

eureka:
  client:
    serviceUrl:
      defaultZone: https://eureka-server-ppq0.onrender.com/eureka/
    fetch-registry: true
    register-with-eureka: true

  instance:
    prefer-ip-address: false
    hostname: auth-service-p0ex.onrender.com
    non-secure-port: 443
    secure-port-enabled: true
    secure-port: 443