server:
  port: ${PORT:8888}

spring:
  application:
    name: config-server

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

  profiles:
    active: native

  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config-repo/

eureka:
  client:
    serviceUrl:
      defaultZone: https://eureka-server-ppq0.onrender.com/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: false
    hostname: api-gateway-qkib.onrender.com