server:
  port: 8083

spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://aipowered-rohithgxwda001-21cd.l.aivencloud.com:14178/defaultdb?sslmode=require}
    username: ${DATABASE_USERNAME:avnadmin}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

genKey: ${GEMINI_API_KEY}

JWT_SECRET: ${JWT_SECRET}

resume-service:
  base-url: ${RESUME_SERVICE_URL:http://localhost:8082}

report-service:
  base-url: ${REPORT_SERVICE_URL:http://localhost:8084}

internal:
  api-key: ${INTERNAL_API_KEY}