server:
  port: ${PORT:8081}
  forward-headers-strategy: framework

spring:
  datasource:
    url: jdbc:postgresql://dpg-danppr3m8hqs73c4qc5g-a:5432/ai_resume_analyser_ioxq
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - openid
              - profile
              - email
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"

jwt:
  secret: ${JWT_SECRET}

frontend:
  base-url: ${FRONTEND_BASE_URL:http://localhost:5173}

notification-service:
  base-url: ${NOTIFICATION_SERVICE_URL:http://localhost:8086}

internal:
  api-key: ${INTERNAL_API_KEY}

eureka:
  client:
    service-url:
      defaultZone: https://eureka-server-ppq0.onrender.com/eureka/
    fetch-registry: true
    register-with-eureka: true

  instance:
    prefer-ip-address: false
    hostname: auth-service-p0ex.onrender.com
    non-secure-port: 443
    secure-port-enabled: true
    secure-port: 443