server:
  port: 8084

spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://aipowered-rohithgxwda001-21cd.l.aivencloud.com:14178/defaultdb?sslmode=require}
    username: ${DATABASE_USERNAME:avnadmin}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

JWT_SECRET: ${JWT_SECRET}

job-service:
  base-url: ${JOB_SERVICE_URL:http://localhost:8085}

internal:
  api-key: ${INTERNAL_API_KEY}