server:
  port: 8084

spring:
  datasource:
    url: jdbc:postgresql://dpg-danppr3m8hqs73c4qc5g-a:5432/ai_resume_analyser_ioxq
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: ${JWT_SECRET}

job-service:
  base-url: ${JOB_SERVICE_URL:http://localhost:8085}

internal:
  api-key: ${INTERNAL_API_KEY}